# Site settings
author: Jeff Swisher
title: 
header-img: img/home-bg.png
email: jefftswisher@gmail.com
copyright_name: Jeff Swisher
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JTSwisher

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
